import ulogging
from networking.wifi import WifiConnection
from networking.uwebsockets.client import WebsocketClient
from config_utils import pull_str_from_config
import typing

logger = ulogging.get_logger("networking_config")

def generate_wifi_connection(config_json: typing.Dict) -> WifiConnection:
    if "wifi" not in config_json.keys():
        raise ValueError("Network config does not have any configuration for wifi")
    wifi_config = config_json["wifi"]
    ssid = pull_str_from_config(config_json=wifi_config, key="ssid", optional=False)
    logger.debug(f"Using WiFi SSID {ssid}")
    password = pull_str_from_config(config_json=wifi_config, key="password", optional=False)
    logger.debug(f"Using password {'*' * len(password)}")
    chosen_hostname = pull_str_from_config(config_json=wifi_config, key="hostname", optional=True)
    if chosen_hostname is None:
        logger.debug("No custom hostname chosen, using an autogenerated one")
        chosen_hostname = ""
    else:
        logger.debug(f"Using hostname {chosen_hostname}")
    return WifiConnection(ssid=ssid, password=password, chosen_hostname=chosen_hostname)

def generate_websocket(network_config_json: typing.Dict, hardware_config_json: typing.Dict, general_config_json: typing.Dict) -> WebsocketClient:
    if "websocket" not in network_config_json.keys():
        raise ValueError("Network config does not have any websocket configuration")
    websocket_config_json = network_config_json["websocket"]
    api_key = pull_str_from_config(config_json=websocket_config_json, key="api_key", optional=False)
    endpoint = pull_str_from_config(config_json=websocket_config_json, key="endpoint", optional=False)
    logger.debug(f"Using base websocket endpoint {endpoint}")
    device_type = pull_str_from_config(config_json=hardware_config_json, key="device_type", optional=False)
    logger.debug(f"Using device type {device_type}")
    # TODO: Check this device type against the DeviceType enum
    device_name = pull_str_from_config(config_json=general_config_json, key="device_name", optional=False)
    logger.debug(f"Using device name {device_name}")
    endpoint = f"{endpoint}/{device_type}/{device_name}"
    logger.debug(f"Final websocket endpoint: {endpoint}")
    return WebsocketClient(api_key=api_key, endpoint=endpoint)


